### PR TITLE
Create restic.md

### PR DESCRIPTION
**Pull request by jdrch**
This guide contains thorough details on how to set up restic on Trident, including environment variable and password file creation.

### CODE REVIEW

**Comment by q5sys** [comment]
Looks good to me, though I'd like Tim to give the grammar a once over when he's got time.

**Comment by jdrch** [comment]
I typically update my guides for grammar, syntax, etc. in multiple iterations after the 1st pull request is approved. You can take a look at the [history](https://github.com/project-trident/trident-docs/commits/master/zfssnap.md) of zfsnap.md (the `zfsnap` guide I wrote) to see what I mean.

**Review by Mrt134 — APPROVED** [review]
Thanks for submitting this guide! I did a quick review of the text and have a couple suggestions to improve readability in future revisions:
- Avoid parenthetical asides when possible. These tend to interrupt sentence flow and can be confusing for the reader.
- Complex sentences joined by multiple comma clauses can be difficult to understand. The reader might find it helpful when long or complicated thoughts are broken down into smaller sentences.

**Comment by jdrch** [comment]
> couple suggestions

Thanks!

> Avoid parenthetical asides when possible

OK. How do you suggest I make points that I prefer to be located close to each other?

*Personally*, I prefer all sequential aspects of a particular feature relevant to my use of it to at least be simultaneously visible. For example: if A, B, and C are useful to know for Step 1 of something, I'd prefer that A, B, and C are simultaneously visible *within* Step 1. This is one of the reasons I struggle heavily with manpages in general. The A, B, and C analogs tend to be VERY far apart, and so it takes me hours to mentally construct what I need to do. It's the entire reason I started writing guides 😉.

> The reader might find it helpful when long or complicated thoughts are broken down into smaller sentences

I'll run through what I wrote and try to reduce these. Thanks.

I should add that my guides are meant to *complement* existing official documentation for functions and features, not supplant or replace them.

**Comment by Mrt134** [comment]
For parentheticals, I generally try to restructure the sentence or paragraph. For example,
```
An example of a crontab schedule is `0	14	*	*	*` (tab separated), which translates to:
```
can be reworked to include the aside and any other important details about crontab schedules as a supporting sentence:
```
Crontab schedules consist of five numeric or asterisk `*` values separated by tabs. For example, `0	14	*	*	*` translates to:
```
or
```
An example crontab schedule is `0	14	*	*	*`. Each value is separated by a tab. This schedule translates to:
```

All that aside, I reviewed the latest changes and the PR looks fine, so I'm going to go ahead and merge the PR. Thanks again for writing and submitting this guide!

**Pull request merged**
